language: ruby
rvm: 
- 1.9.3
- 2.0.0
- 2.1.0
- 2.1.1
- 2.1.2
- 1.8.7
- 1.9.2
- ruby-head
before_install: 
- gem update --system
before_script: 
- gem install rspec rake
script:
- gem build percent-of-change.gemspec && rake travis:v000
- rspec spec --color -f doc
matrix:
  fast_finish: true
  allow_failures:
  - rvm: 1.8.7
  - rvm: 1.9.2
  - rvm: ruby-head
deploy:
  provider: rubygems
  api_key: 769d4095fa3265e5c2e4ecf8e33db7e405f9c436
 
